target-version = "py38"

[lint]
# Enable Pyflakes (`F`) and a subset of the pycodestyle (`E`)  codes by default.
# Unlike Flake8, Ruff doesn't enable pycodestyle warnings (`W`) or
# McCabe complexity (`C901`) by default.
select = ["E", "F", "G", "I", "UP", "AIR", "PIE", "PLR1714", "PLW2901", "TRY201"]
ignore = ["E501"]

[lint.per-file-ignores]
"__init__.py" = [
    "I001", # allow unsorted imports in __init__.py
    "F401", # allow unused imports in __init__.py
]
"examples/*" = [
    "ARG",  # allow unused arguments
    "F841", # allow unused local variables
]
"tests/*" = [
    "ARG",  # allow unused arguments for pytest fixtures
    "E741", # allow reused variables
    "F841", # allow unused local variables
]
