name: Test mango

on:
  push:
    branches:
      - main
      - development
  pull_request:
    types: [opened, synchronize, reopened]


permissions:
  contents: read

jobs:
  build-mac:
    runs-on: macOS-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
        cache-dependency-path: '**/setup.py'
    - name: Install dependencies
      run: |
        pip install virtualenv
        virtualenv venv
        source venv/bin/activate
        pip3 install -U sphinx
        pip3 install -r docs/requirements.txt
        pip3 install -r requirements.txt
        pip3 install -e .
        brew install mosquitto
        brew services start mosquitto
        pip3 install pytest coverage ruff
    - name: Lint with ruff
      run: |
        # stop the build if there are Python syntax errors or undefined names
        source venv/bin/activate
        ruff check .
        ruff format --check .
    - name: Doctests
      run: |
        source venv/bin/activate
        make -C docs doctest
    - name: Test+Coverage
      run: |
        source venv/bin/activate
        coverage run -m pytest
        coverage report

  build-linux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
        cache-dependency-path: '**/setup.py'
    - name: Install dependencies
      run: |
        pip install virtualenv
        virtualenv venv
        source venv/bin/activate
        pip3 install -U sphinx
        pip3 install -r docs/requirements.txt
        pip3 install -r requirements.txt
        pip3 install -e .
        sudo apt update
        sudo apt install --assume-yes mosquitto
        sudo service mosquitto start
        pip3 install pytest coverage ruff
    - name: Lint with ruff
      run: |
        # stop the build if there are Python syntax errors or undefined names
        source venv/bin/activate
        ruff check .
        ruff format --check .
    - name: Doctests
      run: |
        source venv/bin/activate
        make -C docs doctest
    - name: Test+Coverage
      run: |
        source venv/bin/activate
        coverage run -m pytest
        coverage report

  build-win:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
        cache-dependency-path: '**/setup.py'
    - name: Install dependencies
      run: |
        pip install virtualenv
        virtualenv venv
        .\venv\Scripts\activate
        pip3 install -U sphinx
        pip3 install -r docs/requirements.txt
        pip3 install -r requirements.txt
        pip3 install -e .
        pip3 install pytest coverage
        curl.exe -o m.exe https://mosquitto.org/files/binary/win64/mosquitto-2.0.9-install-windows-x64.exe
        dir
        .\m.exe /S
        "C:\Program Files\mosquitto\mosquitto.exe"
    - name: Lint with ruff
      run: |
        # stop the build if there are Python syntax errors or undefined names
        .\venv\Scripts\activate
        python -m ruff check .
        python -m ruff format --check .
    - name: Doctests
      run: |
        .\venv\Scripts\activate
        .\make.bat -C docs doctest
    - name: Test+Coverage
      run: |
        .\venv\Scripts\activate
        python -m coverage run -m pytest
        python -m coverage report
